### ISSUE TITLE
Error installing illustris python

### ISSUE THREAD

**Issue by TheRealEKL** [illustristng/illustris_python#3]
Hello, 

I receive this error while attempting to run the commands to install this package: 

"Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

Any idea how to fix this? Would really appreciate some help, thank you! :)

**Comment by dnelson** [comment]
This is because you are trying to download it via SSH, but haven't set up SSH with github.

You can try instead

```
git clone https://github.com/illustristng/illustris_python.git
```
