### ISSUE TITLE
Sublink numMergers function doesn't loop through the full merger tree

### ISSUE THREAD

**Issue by astrogina** [illustristng/illustris_python#7]
Hello,

I am trying to get the location of mergers within a sublink merger tree, but I believe it only catches mergers that happen along the main progenitor branch (picture included for clarity). 

[<img src="https://github.com/illustristng/illustris_python/assets/60166602/c9e49d27-fbd9-4960-aefc-10f2a0bda350" width="250"/>](https://github.com/illustristng/illustris_python/assets/60166602/c9e49d27-fbd9-4960-aefc-10f2a0bda350)

I wrote a recursive function that loops through the full tree, which I double checked by making sure it matched the number of NextProgenitorIDs > 0 in the tree. 

Here is a pdf of a Jupyter notebook I wrote to illustrate the issue in more detail. 
[finding all mergers.pdf](https://github.com/illustristng/illustris_python/files/13357295/finding.all.mergers.pdf)

I am not sure if this was the intention for the numMergers code. Based on the example provided in the Example Scripts online, I assumed it would walk through the entire tree. I believe the recursive code can be modified to add the minMassRatio check, so if this would be useful for people, I would be happy to submit it in a pull request!

**Comment by dnelson** [comment]
@vrodgom - your thoughts?

**Comment by vrodgom** [comment]
Hi,

I would say that only counting mergers along the main branch is the expected behavior of the numMergers code, since the main branch is usually assumed to represent the "same" object at previous times, and in most applications one is only interested in the number of mergers that a given object had.

If, on the other hand, one is interested in also counting the mergers that the other progenitors had (i.e., mergers of mergers), then a recursive function like the one proposed here would make sense, but I think it really depends on the application.

**Comment by lzkelley** [comment]
Just my two cents after talking with @astrogina: I don't think there's anything wrong with the `numMergers` code, but I do think the description/documentation could be a little more specific.  Right now it says "number of mergers in this sub-tree" whereas it's really the "number of mergers along the main-progenitor branch, in the sub-tree".

**Comment by lblecha** [comment]
I recently ran across this issue independently. Agree that it would be good to note this in the documentation. Fwiw, you can get all mergers in the tree just by adding a recursive call to numMergers() at the end of the second while loop: 
```
while npID != -1:
    
    [ ... ]

    if tree['FirstProgenitorID'][npIndex] != -1:
        numMergersSubtree = numMergers(tree, minMassRatio=minMassRatio, massPartType=massPartType, index=npIndex)
        numMergersTotal += numMergersSubtree
```

**Comment by dnelson** [comment]
Webpage docs also updated.
